---
title: "Assignment 4"
author: "JUFENG_YANG"
date: "2022-10-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Probability theory

In this section we consider some of the concepts introduced in Lecture 9.
Recall that we have introduced the three key rules of probability. Given a sample space Ω along with a
well-behaved collection of events E, a probability P is a function which assigns a number P(A) to each event
A ∈ E, and satisfies rules 1, 2, and 3:
Rule 1: P(A) ≥ 0 for any event A ∈ E
Rule 2: P(Ω) = 1 for sample space Ω
Rule 3: For pairwise disjoint events A1, A2, · · · in E, we have:
\begin{equation *}


\end{equation *}

### 1.1 Rules of probability
#### 1.1 (Q1)
For all probability, We have:
$$
P(\{a\}) + P(\{b\}) = P(\{a,b\}) = 0.6
$$
$$
P(\{b\}) + P(\{c\}) = P(\{b,c\}) = 0.5
$$
$$
P(\{a\}) + P(\{b\}) + P(\{c\}) = 1
$$
We have combine three function, and get P({b}) = 0.1
and P({a}) = 0.5, P({c}) = 0.4

It is easy to get, P(A) > 0, P(\omega) = P({a,b,c}) = 1


#### 1.1 (Q2)
Form the description of the question, we can get for any A event, we have P(A) >= 0. For all cases, 
$$ P(\Omega) = P({0,1}) = 1. $$

For 
$$
P({0}) + P(\{1\}) = 1-q + q = P(\{0,1\}) = 1.
$$
Form above, It follows all 3 rules.


### 1.2 Deriving new properties from the rules of probability
#### 1.2 (Q1)


#### 1.2 (Q2)
For a sample space \omega, we have a event $S$, and a $S^c$. We know $S$ $\bigcup$ $S^c$ = \omega. Accoding to the rule 3, we have, $P(S) + P(S^c) = P(\omega) = 1$

#### 1.2 (Q3)
For any pairwise disjoint events, we have 
$$
\sum_{i=1}^n {\bigcup_{i=1}^n A_i} = \sum_{i=1}^n P(A_i)
$$

But for some cases do not belong to pairwise disjoint, we have a rule,
$$
\sum_{i=1}^n {\bigcup_{i=1}^n A_i} = \sum_{i=1}^n P(A_i) - \sum_{i=1}^n {\bigcap_{i=1}^n A_i}
$$
So, according to this, we have 
$$
\sum_{i=1}^n {\bigcup_{i=1}^n A_i} + \sum_{i=1}^n {\bigcap_{i=1}^n A_i} = \sum_{i=1}^n P(A_i)
$$
If the events is not pairwise disjoint, the $ \sum_{i=1}^n {\bigcap_{i=1}^n A_i} $ will not equal to 0.So we have:
$$
\sum_{i=1}^n {\bigcup_{i=1}^n A_i} < \sum_{i=1}^n P(A_i)
$$
\





